version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - appnet

  node:
    build:
      context: ./node
    image: robertoproj/node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 100s docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
    command: bash -c "npm install express --save && node index.js"
    networks:
      - appnet
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
    image: robertoproj/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - appnet
    depends_on:
      - node



networks:
  appnet:
    driver: bridge